import pytest
from project import bmi_calc, calorie_intake, meal_plan, regulator

def test_bmicalc():
    assert bmi_calc(60,1.8) == 18.52

def test_calorieintake():
    assert calorie_intake(18.52, 'male', 18, 60, 1.8, 'very active') == 2853.15

list = [[{'Food': 'Egg', 'Amount': '1', 'Calories': '69', 'Protein(g)': '6', 'Carbs(g)': '0', 'Fat(g)': '5'}, {'Food': 'Egg white', 'Amount': '1', 'Calories': '16', 'Protein(g)': '4', 'Carbs(g)': '0', 'Fat(g)': '0'}, {'Food': 'Whole grain toast', 'Amount': '2 slices', 'Calories': '170', 'Protein(g)': '8', 'Carbs(g)': '30', 'Fat(g)': '2'}, {'Food': 'Butter', 'Amount': '1 teaspoon', 'Calories': '36', 'Protein(g)': '0', 'Carbs(g)': '0', 'Fat(g)': '4'}, {'Food': 'Blueberries', 'Amount': '10 g', 'Calories': '6', 'Protein(g)': '0.833', 'Carbs(g)': '1.416', 'Fat(g)': '0'}, {'Food': 'TOTAL', 'Amount': '-', 'Calories': '291', 'Protein(g)': '18', 'Carbs(g)': '30', 'Fat(g)': '11'}], [{'Food': 'Protein powder', 'Amount': '3/4 scoop', 'Calories': '89', 'Protein(g)': '18', 'Carbs(g)': '2', 'Fat(g)': '1'}, {'Food': 'Unsweetened almond milk', 'Amount': '250ml', 'Calories': '31', 'Protein(g)': '1', 'Carbs(g)': '0', 'Fat(g)': '3'}, {'Food': 'Banana', 'Amount': '120g', 'Calories': '116', 'Protein(g)': '1', 'Carbs(g)': '28', 'Fat(g)': '0'}, {'Food': 'Natural peanut butter', 'Amount': '10 g', 'Calories': '67.6', 'Protein(g)': '3.2', 'Carbs(g)': '2', 'Fat(g)': '5.2'}, {'Food': 'TOTAL', 'Amount': '-', 'Calories': '236', 'Protein(g)': '20', 'Carbs(g)': '30', 'Fat(g)': '4'}], [{'Food': 'Cooked chicken breast', 'Amount': '80 g', 'Calories': '127', 'Protein(g)': '25', 'Carbs(g)': '0', 'Fat(g)': '3'}, {'Food': 'Cooked broccoli', 'Amount': '125 g', 'Calories': '48', 'Protein(g)': '3', 'Carbs(g)': '9', 'Fat(g)': '0'}, {'Food': 'Cooked white or brown rice', 'Amount': '10 g', 'Calories': '11.083', 'Protein(g)': '0.2916', 'Carbs(g)': '2.2916', 'Fat(g)': '0.0833'}, {'Food': 'TOTAL', 'Amount': '-', 'Calories': '215', 'Protein(g)': '28', 'Carbs(g)': '9', 'Fat(g)': '3'}], [{'Food': 'Oatmeal (dry measurement)', 'Amount': '50 g', 'Calories': '191', 'Protein(g)': '7', 'Carbs(g)': '34', 'Fat(g)': '3'}, {'Food': 'Honey', 'Amount': '1 tablespoon', 'Calories': '72', 'Protein(g)': '0', 'Carbs(g)': '18', 'Fat(g)': '0'}, {'Food': 'Sliced apple', 'Amount': '110 g', 'Calories': '64', 'Protein(g)': '1', 'Carbs(g)': '15', 'Fat(g)': '0'}, {'Food': 'Mixed nuts', 'Amount': '10 g', 'Calories': '65', 'Protein(g)': '2', 'Carbs(g)': '3', 'Fat(g)': '5'}, {'Food': 'TOTAL', 'Amount': '-', 'Calories': '327', 'Protein(g)': '8', 'Carbs(g)': '67', 'Fat(g)': '3'}], [{'Food': 'Cooked sweet potato', 'Amount': '250 g', 'Calories': '232', 'Protein(g)': '5', 'Carbs(g)': '53', 'Fat(g)': '0'}, {'Food': 'Cooked carrots', 'Amount': '125 g', 'Calories': '44', 'Protein(g)': '1', 'Carbs(g)': '10', 'Fat(g)': '0'}, {'Food': 'Extra virgin olive oil', 'Amount': '1 teaspoon', 'Calories': '45', 'Protein(g)': '0', 'Carbs(g)': '0', 'Fat(g)': '5'}, {'Food': 'Cooked lean beef', 'Amount': '10 g', 'Calories': '17.52', 'Protein(g)': '3.058', 'Carbs(g)': '0', 'Fat(g)': '0.5882'}, {'Food': 'TOTAL', 'Amount': '-', 'Calories': '321', 'Protein(g)': '6', 'Carbs(g)': '63', 'Fat(g)': '5'}]]

def test_mealplan():
    assert meal_plan() == list 

def test_regulator():
    assert regulator(list,2853.15) == [[{'Food': 'Egg', 'Amount': '1', 'Calories': '69', 'Protein(g)': '6', 'Carbs(g)': '0', 'Fat(g)': '5'}, {'Food': 'Egg white', 'Amount': '1', 'Calories': '16', 'Protein(g)': '4', 'Carbs(g)': '0', 'Fat(g)': '0'}, {'Food': 'Whole grain toast', 'Amount': '2 slices', 'Calories': '170', 'Protein(g)': '8', 'Carbs(g)': '30', 'Fat(g)': '2'}, {'Food': 'Butter', 'Amount': '1 teaspoon', 'Calories': '36', 'Protein(g)': '0', 'Carbs(g)': '0', 'Fat(g)': '4'}, {'Food': 'Blueberries', 'Amount': '466 g', 'Calories': 280, 'Protein(g)': 39, 'Carbs(g)': 66, 'Fat(g)': 0}, {'Food': 'TOTAL', 'Amount': '-', 'Calories': 571.0, 'Protein(g)': 57.0, 'Carbs(g)': 96.0, 'Fat(g)': 11.0}], [{'Food': 'Protein powder', 'Amount': '3/4 scoop', 'Calories': '89', 'Protein(g)': '18', 'Carbs(g)': '2', 'Fat(g)': '1'}, {'Food': 'Unsweetened almond milk', 'Amount': '250ml', 'Calories': '31', 'Protein(g)': '1', 'Carbs(g)': '0', 'Fat(g)': '3'}, {'Food': 'Banana', 'Amount': '120g', 'Calories': '116', 'Protein(g)': '1', 'Carbs(g)': '28', 'Fat(g)': '0'}, {'Food': 'Natural peanut butter', 'Amount': '50 g', 'Calories': 335, 'Protein(g)': 16, 'Carbs(g)': 10, 'Fat(g)': 26}, {'Food': 'TOTAL', 'Amount': '-', 'Calories': 571.0, 'Protein(g)': 36.0, 'Carbs(g)': 40.0, 'Fat(g)': 30.0}], [{'Food': 'Cooked chicken breast', 'Amount': '80 g', 'Calories': '127', 'Protein(g)': '25', 'Carbs(g)': '0', 'Fat(g)': '3'}, {'Food': 'Cooked broccoli', 'Amount': '125 g', 'Calories': '48', 'Protein(g)': '3', 'Carbs(g)': '9', 'Fat(g)': '0'}, {'Food': 'Cooked white or brown rice', 'Amount': '357 g', 'Calories': 396, 'Protein(g)': 10, 'Carbs(g)': 82, 'Fat(g)': 3}, {'Food': 'TOTAL', 'Amount': '-', 'Calories': 571.0, 'Protein(g)': 38.0, 'Carbs(g)': 91.0, 'Fat(g)': 6.0}], [{'Food': 'Oatmeal (dry measurement)', 'Amount': '50 g', 'Calories': '191', 'Protein(g)': '7', 'Carbs(g)': '34', 'Fat(g)': '3'}, {'Food': 'Honey', 'Amount': '1 tablespoon', 'Calories': '72', 'Protein(g)': '0', 'Carbs(g)': '18', 'Fat(g)': '0'}, {'Food': 'Sliced apple', 'Amount': '110 g', 'Calories': '64', 'Protein(g)': '1', 'Carbs(g)': '15', 'Fat(g)': '0'}, {'Food': 'Mixed nuts', 'Amount': '37 g', 'Calories': 244, 'Protein(g)': 7, 'Carbs(g)': 11, 'Fat(g)': 19}, {'Food': 'TOTAL', 'Amount': '-', 'Calories': 571.0, 'Protein(g)': 15.0, 'Carbs(g)': 78.0, 'Fat(g)': 22.0}], [{'Food': 'Cooked sweet potato', 'Amount': '250 g', 'Calories': '232', 'Protein(g)': '5', 'Carbs(g)': '53', 'Fat(g)': '0'}, {'Food': 'Cooked carrots', 'Amount': '125 g', 'Calories': '44', 'Protein(g)': '1', 'Carbs(g)': '10', 'Fat(g)': '0'}, {'Food': 'Extra virgin olive oil', 'Amount': '1 teaspoon', 'Calories': '45', 'Protein(g)': '0', 'Carbs(g)': '0', 'Fat(g)': '5'}, {'Food': 'Cooked lean beef', 'Amount': '142 g', 'Calories': 250, 'Protein(g)': 44, 'Carbs(g)': 0, 'Fat(g)': 8}, {'Food': 'TOTAL', 'Amount': '-', 'Calories': 571.0, 'Protein(g)': 50.0, 'Carbs(g)': 63.0, 'Fat(g)': 13.0}]]
